<?php
namespace App\Http\Controllers\Api;
use App\Events\QuestionChanged; use App\Http\Controllers\Controller; use App\Models\Event; use App\Models\Question; use App\Models\QuestionVote; use Illuminate\Http\Request; use Illuminate\Support\Facades\RateLimiter; use Illuminate\Validation\Rule;
class PublicEventController extends Controller {
  private function event(string $code): Event { return Event::where('code',$code)->where('is_active',true)->firstOrFail(); }
  private function browserHash(Request $request): string { $id=(string)$request->header('X-Ask-Visitor'); abort_unless(preg_match('/^[a-zA-Z0-9-]{20,80}$/',$id),422,'A browser identifier is required.'); return hash_hmac('sha256',$id,config('app.key')); }
  public function show(string $code) { $event=$this->event($code); return response()->json(['event'=>$this->eventData($event)]); }
  public function qr(string $code) { $event=$this->event($code); return response(\SimpleSoftwareIO\QrCode\Facades\QrCode::format('svg')->size(360)->margin(1)->generate(url('/e/'.$event->code)),200,['Content-Type'=>'image/svg+xml','Cache-Control'=>'public,max-age=3600']); }
  public function questions(Request $request,string $code) { $event=$this->event($code); $sort=$request->string('sort')->value()==='latest'?'latest':'popular'; $query=$event->questions()->whereIn('status',[Question::APPROVED,Question::ANSWERED])->withCount('votes'); $sort==='latest'?$query->latest():$query->orderByDesc('votes_count')->latest(); return response()->json(['questions'=>$query->limit(100)->get()->map(fn($q)=>$this->questionData($q,$event))]); }
  public function storeQuestion(Request $request,string $code) { $event=$this->event($code); $hash=$this->browserHash($request); $key='ask:q:'.$event->id.':'.$hash; abort_if(RateLimiter::tooManyAttempts($key,4),429,'Please wait before submitting another question.'); $data=$request->validate(['body'=>['required','string','min:4','max:1000'],'name'=>['nullable','string','max:80'],'anonymous'=>['nullable','boolean']]); $anonymous=$event->anonymous_enabled && (bool)($data['anonymous']??false); $q=$event->questions()->create(['body'=>trim(strip_tags($data['body'])),'display_name'=>$anonymous?null:(trim(strip_tags($data['name']??'')) ?: null),'is_anonymous'=>$anonymous,'status'=>$event->moderation_enabled?Question::PENDING:Question::APPROVED,'browser_hash'=>$hash]); RateLimiter::hit($key,60); if($q->status===Question::APPROVED) broadcast(new QuestionChanged($q)); return response()->json(['question'=>$this->questionData($q,$event),'message'=>$q->status===Question::PENDING?'Your question is awaiting moderation.':'Your question is now live.'],201); }
  public function vote(Request $request,string $code,Question $question) { $event=$this->event($code); abort_unless($question->event_id===$event->id && $event->upvotes_enabled && in_array($question->status,[Question::APPROVED,Question::ANSWERED],true),404); $hash=$this->browserHash($request); $key='ask:v:'.$question->id.':'.$hash; abort_if(RateLimiter::tooManyAttempts($key,8),429,'Please wait before voting again.'); $vote=QuestionVote::firstOrCreate(['question_id'=>$question->id,'browser_hash'=>$hash]); RateLimiter::hit($key,60); if($vote->wasRecentlyCreated) broadcast(new QuestionChanged($question->fresh())); return response()->json(['voted'=>$vote->wasRecentlyCreated,'votes_count'=>$question->votes()->count()]); }
  private function eventData(Event $e): array { return ['id'=>$e->id,'name'=>$e->name,'code'=>$e->code,'logo_url'=>$e->logo_url,'accent_color'=>$e->accent_color,'screen_background_url'=>$e->screen_background_url,'screen_background_color'=>$e->screen_background_color,'screen_card_color'=>$e->screen_card_color,'screen_highlight_color'=>$e->screen_highlight_color,'screen_text_color'=>$e->screen_text_color,'moderation_enabled'=>$e->moderation_enabled,'anonymous_enabled'=>$e->anonymous_enabled,'upvotes_enabled'=>$e->upvotes_enabled,'show_names'=>$e->show_names]; }
  private function questionData(Question $q,Event $e): array { return ['id'=>$q->id,'body'=>$q->body,'display_name'=>$e->show_names && !$q->is_anonymous?$q->display_name:null,'is_anonymous'=>$q->is_anonymous,'status'=>$q->status,'votes_count'=>(int)($q->votes_count??$q->votes()->count()),'created_at'=>$q->created_at?->toIso8601String()]; }
}
