<?php
namespace Tests\Feature;
use App\Models\Event; use App\Models\Question; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class LiveQaTest extends TestCase {
 use RefreshDatabase;
 private function event(array $overrides=[]):Event{return Event::create(array_merge(['name'=>'Annual Summit','code'=>'summit-2026','accent_color'=>'#9d7a39'], $overrides));}
 private function visitor():array{return ['X-Ask-Visitor'=>'7e5fb220-2bfb-4d8a-85cb-9e1563d1d1ae'];}
 public function test_public_question_is_pending_when_moderation_is_enabled():void{$event=$this->event();$this->postJson('/api/e/'.$event->code.'/questions',['body'=>'What is the next strategic priority?'],$this->visitor())->assertCreated()->assertJsonPath('question.status','pending');$this->assertDatabaseHas('questions',['event_id'=>$event->id,'status'=>'pending']);}
 public function test_public_question_is_approved_when_moderation_is_off():void{$event=$this->event(['code'=>'open-room','moderation_enabled'=>false]);$this->postJson('/api/e/open-room/questions',['body'=>'How will this change next quarter?'],$this->visitor())->assertCreated()->assertJsonPath('question.status','approved');}
 public function test_only_administrators_can_moderate_questions():void{$event=$this->event();$q=$event->questions()->create(['body'=>'Question from audience','status'=>'pending','browser_hash'=>str_repeat('a',64)]);$this->patchJson("/api/admin/events/{$event->id}/questions/{$q->id}",['status'=>'approved'])->assertUnauthorized();$user=User::create(['name'=>'Member','email'=>'member@example.test','password'=>'password','is_admin'=>false]);$this->actingAs($user)->patchJson("/api/admin/events/{$event->id}/questions/{$q->id}",['status'=>'approved'])->assertForbidden();$admin=User::create(['name'=>'Admin','email'=>'admin@example.test','password'=>'password','is_admin'=>true]);$this->actingAs($admin)->patchJson("/api/admin/events/{$event->id}/questions/{$q->id}",['status'=>'approved'])->assertOk()->assertJsonPath('question.status','approved');}
 public function test_duplicate_vote_is_not_counted_twice():void{$event=$this->event();$q=$event->questions()->create(['body'=>'Question from audience','status'=>'approved','browser_hash'=>str_repeat('a',64)]);$this->postJson("/api/e/{$event->code}/questions/{$q->id}/vote",[],$this->visitor())->assertOk()->assertJsonPath('voted',true)->assertJsonPath('votes_count',1);$this->postJson("/api/e/{$event->code}/questions/{$q->id}/vote",[],$this->visitor())->assertOk()->assertJsonPath('voted',false)->assertJsonPath('votes_count',1);$this->assertDatabaseCount('question_votes',1);}
 public function test_rejected_question_does_not_appear_in_public_feed():void{$event=$this->event();$event->questions()->create(['body'=>'Hidden question','status'=>'rejected','browser_hash'=>str_repeat('a',64)]);$event->questions()->create(['body'=>'Visible question','status'=>'approved','browser_hash'=>str_repeat('b',64)]);$this->getJson('/api/e/'.$event->code.'/questions')->assertOk()->assertJsonCount(1,'questions')->assertJsonPath('questions.0.body','Visible question');}
}
